---
client:
  restart_in_place: false
  read_local_logs: true
  show_confirmation_questions: false
  show_expanded_aliases: true
  dark_mode: false
  max_status_lines: ~
  status_time_format: "%H:%M:%S"
  status_datetime_format: "%Y-%m-%d\n%H:%M:%S"
daemon:
  pause_group_on_failure: false
  pause_all_on_failure: false
  callback: ~
  callback_log_lines: 10
shared:
  pueue_directory: ~/data/pueue/
  runtime_directory: ~/data/pueue/
  use_unix_socket: true
  pid_path: ~/.local/share/pueue/pid
  unix_socket_path: ~/.local/share/pueue/sock
  host: 127.0.0.1
  port: "6924"
  daemon_cert: ~/data/pueue/sec/cert
  daemon_key: ~/data/pueue/sec/key
  shared_secret_path: ~/data/pueue/sec/shared
profiles: {}
