###################
# General Settings
####################

env:
  TERM: alacritty

# Font
font:
  normal:
    family: Liberation Mono
    style: Regular
  bold:
    family: Liberation Mono
    style: Bold
  italic:
    family: Liberation Mono
    style: Italic
  bold_italic:
    family: Liberation Mono
    style: Bold Italic
  size: 12

# Colors
colors:
  primary:
    background: '#000000'
    foreground: '#ffffff'
  normal:
    black: '#000000'
    white: '#ffffff'
    red: '#ff0000'
    green: '#00ff00'
    blue: '#4040ff'
    yellow: '#ffff00'
    magenta: '#ff00ff'
    cyan: '#00ffff'

scrolling:
  history: 100000
  multiplier: 3

# Visual Bell
bell:
  animation: Ease
  duration: 10
  color: '0xffffff'

# Window stuff
window.opacity: 1.0

url:
  Default:
    - None
  launcher:
    program: None
  modifiers: Alt

####################
# Key bindings
####################

key_bindings:
  # general terminal controls
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: J, mods: Control|Shift, action: ScrollLineDown }
  - { key: K, mods: Control|Shift, action: ScrollLineUp }
  - { key: H, mods: Control|Shift, action: ScrollPageDown }
  - { key: L, mods: Control|Shift, action: ScrollPageUp }
  - { key: Minus, mods: Alt, action: DecreaseFontSize }
  - { key: Plus, mods: Alt|Shift, action: ResetFontSize }
  - { key: Equals, mods: Alt, action: IncreaseFontSize }
  - { key: Return, mods: Command|Shift, action: SpawnNewInstance }
  - { key: Return, mods: Control, chars: "!!\n" }
  - { key: Back, mods: Alt, chars: "clear\n" }
  - { key: Escape, mods: Alt, action: ToggleViMode }
  # ctrl+shift
  - { key: A, mods: Control|Shift, chars: "\x1b[65;5u" }
  - { key: B, mods: Control|Shift, chars: "\x1b[66;5u" }
  - { key: D, mods: Control|Shift, chars: "\x1b[68;5u" }
  - { key: E, mods: Control|Shift, chars: "\x1b[69;5u" }
  - { key: F, mods: Control|Shift, chars: "\x1b[70;5u" }
  - { key: G, mods: Control|Shift, chars: "\x1b[71;5u" }
  # - { key: H, mods: Control|Shift, chars: "\x1b[72;5u" }
  - { key: I, mods: Control|Shift, chars: "\x1b[73;5u" }
  # - { key: J, mods: Control|Shift, chars: "\x1b[74;5u" }
  # - { key: K, mods: Control|Shift, chars: "\x1b[75;5u" }
  # - { key: L, mods: Control|Shift, chars: "\x1b[76;5u" }
  - { key: M, mods: Control|Shift, chars: "\x1b[77;5u" }
  - { key: N, mods: Control|Shift, chars: "\x1b[78;5u" }
  - { key: O, mods: Control|Shift, chars: "\x1b[79;5u" }
  - { key: P, mods: Control|Shift, chars: "\x1b[80;5u" }
  - { key: Q, mods: Control|Shift, chars: "\x1b[81;5u" }
  - { key: R, mods: Control|Shift, chars: "\x1b[82;5u" }
  - { key: S, mods: Control|Shift, chars: "\x1b[83;5u" }
  - { key: T, mods: Control|Shift, chars: "\x1b[84;5u" }
  - { key: U, mods: Control|Shift, chars: "\x1b[85;5u" }
  - { key: W, mods: Control|Shift, chars: "\x1b[87;5u" }
  - { key: X, mods: Control|Shift, chars: "\x1b[88;5u" }
  - { key: Y, mods: Control|Shift, chars: "\x1b[89;5u" }
  - { key: Z, mods: Control|Shift, chars: "\x1b[90;5u" }
