#!/usr/bin/python3

import sys
import eyed3

for file in sys.argv[1:]:
    if file.endswith(".mp3"):
        try:
            f = eyed3.load(file)
            arr = file.strip(".mp3").split(" - ")
            if len(arr) > 1:
                f.tag.artist = arr[-1]
            else:
                print(f"[!] File {file} doesn't have an artist")
            f.tag.title = " - ".join(arr[:-1])
            f.tag.save()
        except Exception as e:
            print(f"[!] File {file} couldn't be retagged: " + str(e))
    else:
        print(f"[!] File {file} is not an mp3 file")
