#!/usr/bin/python3
import sys,urllib.parse

if len(sys.argv) == 1:
    # use stdin
    for line in sys.stdin:
        print(urllib.parse.unquote(line), end="")
else:
    for i in sys.argv[1:]:
        print(urllib.parse.unquote(i), end="")
